### ISSUE TITLE
missing response handling

### ISSUE THREAD

**Issue by toshok** [honeycombio/libhoney-js#1]
part of the honeycomb sdk spec deals with how to handle responses from the api host: http://localhost:1313/docs/send-data/sdks/#responses

the JS sdk is different from go/python in that it can't assume threads, so maybe we can:
1. opportunistically steal some cycles from the main event loop to make sure the response queue doesn't grow without bound?
2. return a promise from the `send` apis and deal with the response locally?

neither sounds particularly nice.

**Comment by robbkidd** [comment]
We’re going to close this for now from inactivity. Feel free to re-open if the issue described here is still relevant.
