### ISSUE TITLE
v2.2.2 does not include the compiled code, and crashes the process when required

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/libhoney-js#107]
If you attempt to `require` the package the nodejs process crashes because the `libhoney.cjs.js` file does not exist in the package:

![image](https://user-images.githubusercontent.com/20394/112195692-27c55880-8c02-11eb-9828-c38fa85e051e.png)

Here is a runkit link that reproduces the behaviour: https://runkit.com/brmatt/runkit-npm-libhoney

I have a feeling this might affect several users of the package because `beeline-nodejs` has a dependency on `"libhoney": "^2.2.1"`, which would appear to treat `2.2.2` as a safe upgrade.

**Comment by vreynolds** [comment]
v2.2.2 has been unlisted and re-published as 2.2.3 with the the right dist files.
