### ISSUE TITLE
docs for libhoney options

### ISSUE THREAD

**Issue by toshok** [honeycombio/libhoney-js#11]
right now the docs for libhoney's constructor don't mention any of the properties you can override:
![screen shot 2017-04-03 at 11 55 02 am](https://cloud.githubusercontent.com/assets/24245/24625597/6855c706-1864-11e7-8d7e-50a80b2ba43e.png)

this is pretty terrible, but I couldn't figure out how to get esdoc to let me specify name/type/attribute/description for each of the properties.

**Comment by robbkidd** [comment]
We’re going to close this for now from inactivity. Feel free to re-open if the issue described here is still relevant.
