### ISSUE TITLE
Could you publish 1.0.0-beta8

### ISSUE THREAD

**Issue by evanderkoogh** [honeycombio/libhoney-js#14]
The disabled flag isn't actually in the released version on npm. This is currently my initial setup:

```javascript
const hny = new Libhoney({
    writeKey: process.env.HONEYCOMB_WRITE_KEY || 'something-non-empty',
    dataset: process.env.HONEYCOMB_DATASET || 'linc-local-serve',
    disabled: !process.env.HONEYCOMB_WRITE_KEY
});
```
Not pretty, but if I don't have the `|| 'something-non-empty'` I get a validation error for every request when no WRITE_KEY is passed in.

**Comment by toshok** [comment]
So sorry, I thought I had.  Thanks for the ping!
