### ISSUE TITLE
No-yarn engine requirement breaks use as dependency

### ISSUE THREAD

**Issue by twpol** [honeycombio/libhoney-js#169]
This line breaks any downstream project which wishes to use Yarn, even transitively via `honeycomb-beeline`:

https://github.com/honeycombio/libhoney-js/blob/a8cee1a36766aef93223acba18fb897f89c8717f/package.json#L12

```
error libhoney@2.3.1: The engine "yarn" is incompatible with this module. Expected version "YARN NO LONGER USED - use npm instead.". Got "1.22.5"
error Found incompatible module.
```

I'm guessing you didn't _intentionally_ block all downstream projects from using Yarn :)

**Comment by rcunning** [comment]
Hi libhoney folks - yeah, same issue. This is blocking our builds right now. Can we get an ETA for fixing?

**Comment by markandrus** [comment]
Short-term workaround:

```
yarn install --ignore-engines
```

**Comment by robbkidd** [comment]
Ooo. Forcing everyone downstream off yarn was _not_ the intention there! We'll get on a new patch release.

**Comment by robbkidd** [comment]
Fix merged. Expect a release out shortly (today).

**Comment by robbkidd** [comment]
[v2.3.2](https://www.npmjs.com/package/libhoney/v/2.3.2) is out now with the anti-yarn sentiment removed. Thanks, everybody!
