### ISSUE TITLE
Dynamic Field registration time

### ISSUE THREAD

**Issue by rgbkrk** [honeycombio/libhoney-js#17]
Within the express example, the dynamic fields are added on every call to the middleware:

https://github.com/honeycombio/libhoney-js/blob/f90a4a6136da1bb0bcc8918179391cb46e7e4770/examples/express-dynamic-fields/express-honey.js#L4-L13

Is this required behavior or can you register these callbacks before that function declaration?

**Comment by christineyen** [comment]
Definitely not required behavior, and definitely not great to put forth as an example usage of Honeycomb. Thanks for the note!

**Comment by christineyen** [comment]
Merged! Thanks again.

**Comment by rgbkrk** [comment]
Thank you!
