### ISSUE TITLE
Missing default to new Date()

### ISSUE THREAD

**Issue by perplexes** [honeycombio/libhoney-js#20]
In Ruby this is: https://github.com/honeycombio/libhoney-rb/blob/bacadc7ae70ebe4cf8f68cca628f375a337f3a77/lib/libhoney/event.rb#L21

And I would expect the same here: https://github.com/honeycombio/libhoney-js/blob/fdf579f931d127a3a351e125b85c200f24c0852f/src/event.js#L58

Not sure if this results in missing timestamps, or they get filled in at the event collector.

**Comment by robbkidd** [comment]
We’re going to close this for now from inactivity. Feel free to re-open if the issue described here is still relevant.
