### ISSUE TITLE
web worker transmission implementation

### ISSUE THREAD

**Issue by toshok** [honeycombio/libhoney-js#22]
This is perhaps less of a problem now that batch support is in, but ideally the cost of using libhoney from within a webpage would be essentially zero.

If we can push all the batching/sending to a web worker, we should absolutely do that.

**Comment by ChristopherBiscardi** [comment]
I wonder if [workerize](https://github.com/developit/workerize) would help us here

**Comment by toshok** [comment]
oh cool.  yeah, possibly.  there is some bidi communication (needed to service response queue) but maybe some refactoring could put that solely on the libhoney-side of the worker.

**Comment by coccyx** [comment]
Might keep an eye on this as well: https://nodejs.org/api/worker_threads.html

Not stable yet, but coming fast.

**Comment by robbkidd** [comment]
We’re going to close this for now from inactivity. Feel free to re-open if the issue described here is still relevant.
