### ISSUE TITLE
Date range picker issues

### ISSUE THREAD

**Issue by kathiravan07** [honeycombio/libhoney-js#295]
When shows only past 60 days dates in date range calendar. But when we select current month date its shows future month date also

Please let me know any face this issues before

**Comment by vreynolds** [comment]
Hello! It sounds like you have a question about Honeycomb UI. This repository is the JavaScript SDK for emitting telemetry and does not handle the UI. Could you please forward your questions to [support](https://www.honeycomb.io/support/)?
