### ISSUE TITLE
newBuilder on top-level Libhoney doesn't copy props

### ISSUE THREAD

**Issue by ebroder** [honeycombio/libhoney-js#4]
I could be doing something wrong, but it looks like https://github.com/honeycombio/libhoney-js/blob/f7ce6c0ab566a2ec2ff96e9ccad394bc0c9a2382/src/libhoney.js#L208 won't work as intended, because it tries to grab `this._fields` and `this._dyn_fields`, when it seems like the relevant values are stored on `this._builder`.

**Comment by toshok** [comment]
ah, great catch.  You're totally correct, libhoney's `newBuilder` should proxy to `this._builder.newBuilder`.  fix incoming.
