### ISSUE TITLE
Calling Libhoney.flush() results in TypeError when options.disabled === true

### ISSUE THREAD

**Issue by schellack** [honeycombio/libhoney-js#56]
I recently started using Libhoney and it's been great. Thanks for your work on it!

I ran into one issue, described below:

### Issue Description

When Libhoney is initialized with the option `disabled` set to true, subsequent calls to the flush function on the instance of Libhoney result in a TypeError:

> TypeError: Cannot read property 'flush' of null

This happens because the [`getAndInitTransmission` function returns null when disabled is set to true](https://github.com/honeycombio/libhoney-js/blob/1c65b1e652d21f193ecb92a4355e8766c271924a/src/libhoney.js#L456).

The [`flush` function](https://github.com/honeycombio/libhoney-js/blob/1c65b1e652d21f193ecb92a4355e8766c271924a/src/libhoney.js#L421) calls `getAndInitTransmission`, gets null back, and then tries to call the flush function of the result of the call to `getAndInitTransmission`:
```
 flush() {
    const transmission = this._transmission;

    this._transmission = getAndInitTransmission(
      this._options.transmission,
      this._options
    );

    return transmission.flush();
  }
```

This results in the TypeError.

### Steps to reproduce

1. Create a new JavaScript file (I'm running unit tests with Jest, but this should work regardless of how you want to host your process)
2. Import Libhoney and create a new instance of the Libhoney class (make sure to set disabled to true):
```
import Libhoney from 'libhoney';
const honey = new Libhoney({
  writeKey: 'someKey',
  dataset: 'someDataSet',
  disabled: true,
});
```
3. Send an event:
```
honey.send({
  message: "Test Honeycomb event",
});
```
4. Call `honey.flush();` and see the error

## Additional Information

I'm happy to submit a pull request but would want advice on if you would prefer to return from the Libhoney flush function if getAndInitTransmission returns null or handle in some other way to let the caller know that nothing is happening.

Here's my stack trace, if that helps:

>       at Libhoney.flush (node_modules/libhoney/dist/libhoney.cjs.js:1274:25)
>       at flush (handler.js:111:26)
>       at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
>       at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
>       at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
>       at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
>       at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
