### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by bondarewicz** [honeycombio/libhoney-js#60]
Trying to use `libhoney` directly from the browser ([CRA](https://github.com/facebook/create-react-app) built with webpack)

```js
import Libhoney from "libhoney";

let hny = new Libhoney({
  writeKey: "API_KEY",
  dataset: "DATASET_NAME",
  // disabled: true, // uncomment for testing or development.
  responseCallback: responses => {
    responses.forEach(resp => {
      console.log(resp);
    });
  }
});


let params = {
  hostname: window.location.href,
  applicationName: "test"
}

hny.add(params);

let builder = hny.newBuilder({ built: true });
let event = builder.newEvent();

event.addField("applicationName", "test");
event.addField("correlationId", "8f962726-57fc-441f-ab14-010a1921172e");

event.timestamp = new Date(Date.UTC(2016, 1, 29, 1, 1, 1));
event.metadata = { id: "recognize-me-later" };
event.send();
```

results in console output : 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.honeycomb.io/1/batch/datasetnamehere. 
(Reason: missing token 'content-type' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.honeycomb.io/1/batch/datasetnamehere. 
(Reason: CORS request did not succeed).

{"duration":294,"metadata":{"id":"recognize-me-later"},"error":{"crossDomain":true,"method":"POST","url":"https://api.honeycomb.io/1/batch/DATASET_NAME"}}
```

preflight requests are made to: 

```
Request URL:https://api.honeycomb.io/1/batch/DATASET_NAME
Request method:OPTIONS
Remote address:REDACTED:443
Status code:200
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade
```

Request headers:

```
Host: api.honeycomb.io
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: */*
Accept-Language: en-GB,pl;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type,user-agent,x-hny-team
Referer: http://localhost:3000/test
Origin: http://localhost:3000
Connection: keep-alive
```

Response headers

```
Host: api.honeycomb.io
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: */*
Accept-Language: en-GB,pl;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type,user-agent,x-hny-team
Referer: http://localhost:3000/test
Origin: http://localhost:3000
Connection: keep-alive
```

Did anyone came across same/similiar issue?

**Comment by toshok** [comment]
yeah, this is an issue on the api side of things.  will pass it along.

**Comment by bondarewicz** [comment]
I just received a message that `Access-Control-Allow-Origin: *` header have been added, I can confirm that it's now being exposed, however  `Access-Control-Allow-Headers` still appear to be missing `content-type` 

In addtion to above there's a mismatch in request & response headers resulting in
```
Access to XMLHttpRequest at 'https://api.honeycomb.io/1/batch/DATASET_NAME' from origin 'http://localhost:3000' has been blocked by CORS policy: 
Request header field x-hny-team is not allowed by Access-Control-Allow-Headers in preflight response.
```

![Screenshot 2019-10-30 at 15 22 28](https://user-images.githubusercontent.com/435051/67874619-12dbb700-fb2d-11e9-83cf-7f26c6480a58.png)

**Comment by toshok** [comment]
ah, content-type is not one of the whitelisted types.  going to add that to the api server now.

**Comment by bondarewicz** [comment]
@toshok ok, we would need "User-Agent" header (which is used to report on lib ver) to be whitelisted as well:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.honeycomb.io/1/batch/DATASET_NAME. 
(Reason: missing token 'user-agent' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel).
```

I've commented out (temporarily) this [line](https://github.com/honeycombio/libhoney-js/blob/master/src/transmission.js#L315) on my machine and can confirm that I can now see logs in the dataset and both chrome & firefox does not report anymore CORS related warnings

**Comment by toshok** [comment]
yeah browsers don't let you set `User-Agent` on outgoing requests.  I was hoping that they'd just ignore the set, but chrome at least appears to throw an exception.

**Comment by toshok** [comment]
hm, it actually looks like it's just a console.error - the request goes through

**Comment by toshok** [comment]
Going to mark this fixed once the API User-Agent change goes in, since the local setting of User-Agent doesn't seem to actually kill requests (does it on other browsers?)

I'd love to hear about how you're getting around the bundling of libhoney into a browser bundle given the transitive deps on things like `net` and `tls` thanks to the `superagent-proxy` dep.

**Comment by toshok** [comment]
This should be fixed now that the api changes have landed.
