### ISSUE TITLE
Support for writing to STDOUT for AWS users?

### ISSUE THREAD

**Issue by wolfeidau** [honeycombio/libhoney-js#62]
The Go and Python libraries currently support the ability to emit events to stdout, is this a supported configuration planned for this library? 

I found a way of enabling it by setting `transmission` to `writer` and a place holder key  which is required but not used currently.

 Sadly this configuration almost works, the JSON is emitted as a quoted string, I am not sure why.

```
"{\"time\":\"2019-11-08T23:35:26.136Z\",\"samplerate\":1,\"data\":{\"meta.local_hostname\":\"test\",\"service_name\":\"my-lambda-service\",\"meta.type\":\"fastify\",\"meta.package_version\":\"2.10.0\",\"name\":\"request\",\"trace.trace_id_source\":null,\"request.host\":\"localhost:3000\",\"request.original_url\":\"/\",\"request.remote_addr\":\"127.0.0.1\",\"request.method\":\"GET\",\"request.route\":null,\"request.query\":{},\"request.http_version\":\"HTTP/1.1\",\"trace.trace_id\":\"7a033493-5bec-490c-a811-995053787d1e\",\"trace.span_id\":\"11071ea0-f247-44d3-a659-3fd4de12574f\",\"duration_ms\":7.573277,\"response.status_code\":\"200\",\"meta.instrumentations\":[\"fastify\",\"http\",\"https\"],\"meta.instrumentation_count\":3,\"meta.beeline_version\":\"1.8.3\",\"meta.node_version\":\"v12.8.0\"}}"
```

I am keen to use this library with AWS lambda in concert with the cloudwatch logs and https://github.com/honeycombio/honeyaws as access to the endpoints in the US add latency to our lambda operations.

**Comment by vreynolds** [comment]
Released in [v2.3.0](https://github.com/honeycombio/libhoney-js/releases/tag/v2.3.0)
