### ISSUE TITLE
Unable to include in build with Webpack for browsers

### ISSUE THREAD

**Issue by twpol** [honeycombio/libhoney-js#63]
I'm trying to include `libhoney-js` in a webpack build for the browser, but it results in a whole load of failures to find NodeJS modules `dns`, `fs`, `net`, and `tls` as part of the `superagent-proxy` dependent module included here:

https://github.com/honeycombio/libhoney-js/blob/2fe34fef63e10028eacba82d7f3e9bc73e729b63/src/transmission.js#L10

Commenting out the `superagent-proxy` import in `dist/libhoney.es.js` resolves the problem.

My webpack configuration is nothing (no conf file at all), and this is the line I use to include `libhoney-js`:

```js
import libhoney from 'libhoney'
```

I suppose that this dependent module isn't meant to work in the browser, although `libhoney-js` says it itself does - is this meant to be supported, or should I give up now? :)

**Comment by martin308** [comment]
@twpol one way to fix this is to tell webpack to not include this dependency in the bundle. You won't be able to use the proxy functionality but it will allow you to build and use this in the browser.

Sample webpack.config.js, the important section is `externals`:

```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  externals: {
    'superagent-proxy': 'superagent-proxy',
  },
  plugins: [new HtmlWebpackPlugin()]
};
```
