### ISSUE TITLE
Does this library support gzip-level-1 compression?

### ISSUE THREAD

**Issue by dko-slapdash** [honeycombio/libhoney-js#64]
Hi.

I noticed that Go version of libhoney does gzip compression, and most likely it HUGELY optimizes the ingestion traffic.

Is there a simple way to enable gzip compression level 1 for Node version too?

**Comment by toshok** [comment]
There isn't at the moment.  There is a node module for doing gzip compression that we can pull in, but the JS SDK has the added constraint of having to run in the browser as well.

Unless of course there's native node support for gzip compression in http/https based on header values for requests, but I didn't see anything like that when I last looked.

**Comment by robbkidd** [comment]
We’re going to close this for now from inactivity. Feel free to re-open if the issue described here is still relevant.
