### ISSUE TITLE
'User-Agent' header console error in Browser (detect if in browser and avoid setting UA)

### ISSUE THREAD

**Issue by PDickeyTruss** [honeycombio/libhoney-js#67]
When using libhoney-js to send events/spans to Honeycomb, Chrome and Safari log a console error stating :`client.js:759 Refused to set unsafe header "User-Agent"`. Per discussion in the Honeycomb Pollinator #general channel, it should be detected that we're running in a browser and avoid setting the User-Agent header. The UA is set in line 311 of transmission.js: https://github.com/honeycombio/libhoney-js/blob/master/src/transmission.js#L311

**Comment by toshok** [comment]
Feels like the best way to do this is to check for node, instead of checking for browser.

```
typeof process
```

should work?
